/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as PrefectureSlugRouteImport } from './routes/prefecture.$slug'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as RegionSlugRouteImport } from './routes/region.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrefectureSlugRoute = PrefectureSlugRouteImport.update({
  id: '/prefecture/$slug',
  path: '/prefecture/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionSlugRoute = RegionSlugRouteImport.update({
  id: '/region/$slug',
  path: '/region/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/consult': typeof ConsultRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/pricing': typeof PricingRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prefecture/$slug': typeof PrefectureSlugRoute
  '/property/$id': typeof PropertyIdRoute
  '/region/$slug': typeof RegionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/consult': typeof ConsultRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/pricing': typeof PricingRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prefecture/$slug': typeof PrefectureSlugRoute
  '/property/$id': typeof PropertyIdRoute
  '/region/$slug': typeof RegionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/consult': typeof ConsultRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/pricing': typeof PricingRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prefecture/$slug': typeof PrefectureSlugRoute
  '/property/$id': typeof PropertyIdRoute
  '/region/$slug': typeof RegionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/consult'
    | '/login'
    | '/map'
    | '/pricing'
    | '/saved'
    | '/search'
    | '/category/$slug'
    | '/prefecture/$slug'
    | '/property/$id'
    | '/region/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/consult'
    | '/login'
    | '/map'
    | '/pricing'
    | '/saved'
    | '/search'
    | '/category/$slug'
    | '/prefecture/$slug'
    | '/property/$id'
    | '/region/$slug'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/consult'
    | '/login'
    | '/map'
    | '/pricing'
    | '/saved'
    | '/search'
    | '/category/$slug'
    | '/prefecture/$slug'
    | '/property/$id'
    | '/region/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRoute
  ConsultRoute: typeof ConsultRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PricingRoute: typeof PricingRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PrefectureSlugRoute: typeof PrefectureSlugRoute
  PropertyIdRoute: typeof PropertyIdRoute
  RegionSlugRoute: typeof RegionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prefecture/$slug': {
      id: '/prefecture/$slug'
      path: '/prefecture/$slug'
      fullPath: '/prefecture/$slug'
      preLoaderRoute: typeof PrefectureSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/$slug': {
      id: '/region/$slug'
      path: '/region/$slug'
      fullPath: '/region/$slug'
      preLoaderRoute: typeof RegionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRoute,
  ConsultRoute: ConsultRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PricingRoute: PricingRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  CategorySlugRoute: CategorySlugRoute,
  PrefectureSlugRoute: PrefectureSlugRoute,
  PropertyIdRoute: PropertyIdRoute,
  RegionSlugRoute: RegionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
