/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as JapanPropertiesRouteImport } from './routes/japan-properties'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as UsPropertiesRouteImport } from './routes/us-properties'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as PrefectureSlugRouteImport } from './routes/prefecture.$slug'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as RegionSlugRouteImport } from './routes/region.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin/$id'
import { Route as AuthenticatedAdminNewRouteImport } from './routes/_authenticated/admin/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const JapanPropertiesRoute = JapanPropertiesRouteImport.update({
  id: '/japan-properties',
  path: '/japan-properties',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UsPropertiesRoute = UsPropertiesRouteImport.update({
  id: '/us-properties',
  path: '/us-properties',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrefectureSlugRoute = PrefectureSlugRouteImport.update({
  id: '/prefecture/$slug',
  path: '/prefecture/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionSlugRoute = RegionSlugRouteImport.update({
  id: '/region/$slug',
  path: '/region/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminNewRoute = AuthenticatedAdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/consult': typeof ConsultRoute
  '/japan-properties': typeof JapanPropertiesRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/pricing': typeof PricingRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/us-properties': typeof UsPropertiesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prefecture/$slug': typeof PrefectureSlugRoute
  '/property/$id': typeof PropertyIdRoute
  '/region/$slug': typeof RegionSlugRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/consult': typeof ConsultRoute
  '/japan-properties': typeof JapanPropertiesRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/pricing': typeof PricingRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/us-properties': typeof UsPropertiesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prefecture/$slug': typeof PrefectureSlugRoute
  '/property/$id': typeof PropertyIdRoute
  '/region/$slug': typeof RegionSlugRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/articles': typeof ArticlesRoute
  '/consult': typeof ConsultRoute
  '/japan-properties': typeof JapanPropertiesRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/pricing': typeof PricingRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/us-properties': typeof UsPropertiesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prefecture/$slug': typeof PrefectureSlugRoute
  '/property/$id': typeof PropertyIdRoute
  '/region/$slug': typeof RegionSlugRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/new': typeof AuthenticatedAdminNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/consult'
    | '/japan-properties'
    | '/login'
    | '/map'
    | '/pricing'
    | '/saved'
    | '/search'
    | '/us-properties'
    | '/category/$slug'
    | '/prefecture/$slug'
    | '/property/$id'
    | '/region/$slug'
    | '/admin/$id'
    | '/admin/new'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/consult'
    | '/japan-properties'
    | '/login'
    | '/map'
    | '/pricing'
    | '/saved'
    | '/search'
    | '/us-properties'
    | '/category/$slug'
    | '/prefecture/$slug'
    | '/property/$id'
    | '/region/$slug'
    | '/admin/$id'
    | '/admin/new'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/articles'
    | '/consult'
    | '/japan-properties'
    | '/login'
    | '/map'
    | '/pricing'
    | '/saved'
    | '/search'
    | '/us-properties'
    | '/category/$slug'
    | '/prefecture/$slug'
    | '/property/$id'
    | '/region/$slug'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/new'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArticlesRoute: typeof ArticlesRoute
  ConsultRoute: typeof ConsultRoute
  JapanPropertiesRoute: typeof JapanPropertiesRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PricingRoute: typeof PricingRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  UsPropertiesRoute: typeof UsPropertiesRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PrefectureSlugRoute: typeof PrefectureSlugRoute
  PropertyIdRoute: typeof PropertyIdRoute
  RegionSlugRoute: typeof RegionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/japan-properties': {
      id: '/japan-properties'
      path: '/japan-properties'
      fullPath: '/japan-properties'
      preLoaderRoute: typeof JapanPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us-properties': {
      id: '/us-properties'
      path: '/us-properties'
      fullPath: '/us-properties'
      preLoaderRoute: typeof UsPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prefecture/$slug': {
      id: '/prefecture/$slug'
      path: '/prefecture/$slug'
      fullPath: '/prefecture/$slug'
      preLoaderRoute: typeof PrefectureSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/$slug': {
      id: '/region/$slug'
      path: '/region/$slug'
      fullPath: '/region/$slug'
      preLoaderRoute: typeof RegionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/new': {
      id: '/_authenticated/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminNewRoute: typeof AuthenticatedAdminNewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminNewRoute: AuthenticatedAdminNewRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArticlesRoute: ArticlesRoute,
  ConsultRoute: ConsultRoute,
  JapanPropertiesRoute: JapanPropertiesRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PricingRoute: PricingRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  UsPropertiesRoute: UsPropertiesRoute,
  CategorySlugRoute: CategorySlugRoute,
  PrefectureSlugRoute: PrefectureSlugRoute,
  PropertyIdRoute: PropertyIdRoute,
  RegionSlugRoute: RegionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
